# Generated by Django 4.2.4 on 2023-08-29 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("order_left", models.IntegerField(null=True)),
                ("order_right", models.IntegerField(null=True)),
                (
                    "item_complete_action",
                    models.CharField(
                        choices=[("DEL", "Delete"), ("STR", "Strike"), ("CHE", "Check")], default="CHE", max_length=3
                    ),
                ),
                ("hide_completed", models.BooleanField(default=False)),
                ("hide_until_due", models.BooleanField(default=False)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                ("order_left", models.IntegerField()),
                ("order_right", models.IntegerField()),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="checklists.checklist"
                    ),
                ),
            ],
        ),
    ]
